### ISSUE TITLE
Publish webpack directory / plugins

### ISSUE THREAD

**Issue by niieani** [mikemintz/rethinkdb-websocket-client#10]
Webpack plugins should be published in the NPM repository for custom scenarios. In my case, I want to use `rethinkdbdash` as the client instead of the standard one combined with your `TcpPolyfillPlugin` and `TlsStubPlugin`. I was able to copy& paste those plugins and configure Webpack with a custom `target` to load them for `rethinkdbdash`. If the plugins were published it would have been an easier process :)

**Comment by mikemintz** [comment]
@niieani do you have an example of a webpack plugin that's published to NPM? I'd be curious to see their package.json file so I make sure I do it correctly.

**Comment by niieani** [comment]
Well I think you could just remove the Webpack directory from .npmignore or add it to `files` list (whichever way of publishing you're using) of this package. Webpack's internal plugins are also published like that, accessible by path: `require('webpack/lib/somePlugin')`.

I maintain a [Webpack Plugin](https://github.com/aurelia/webpack-plugin) myself and in my case the `main` of the package.json points to the file exporting the plugin. 
Here's another popular plugin for reference: https://github.com/ampedandwired/html-webpack-plugin.

**Comment by mikemintz** [comment]
I added the webpack directory to `files` in package.json and published 0.5.0. I'll mark this as closed, but feel free to re-open if there are any issues with it.
