### ISSUE TITLE
Question about Secure Feature

### ISSUE THREAD

**Issue by manglav** [mikemintz/rethinkdb-websocket-client#13]
What is the proper way to use the secure feature with the corresponding rethinkdb-websocket server?  I have a rethinkdb server running on AWS. Created my SSL keys.  The ws server seems to connect fine, but my browser clients can no longer connect.

**Comment by mikemintz** [comment]
If you're running rethinkdb-websocket-server behind secure websockets with SSL keys, then you need to set `secure: true` in the options for `RethinkdbWebsocketClient.connect`. If that isn't working, you can also test that the websocket is connecting at all. Maybe something like https://www.websocket.org/echo.html will be helpful, where you can type `wss://ec2-host-name-goes-here` and see if it'll connect with secure websockets.

**Comment by manglav** [comment]
Yeah I got it working in the end, but it was a big pain. Thanks for your help.
